<?php

return [
    'page_title' => [
        'create_brand' => 'ایجاد برند',
        'brand' => 'برندها',
        'create_category' => 'ایجاد دسته بندی',
        'category' => 'دسته بندی',
        'comment' => 'نظرات',
        'show_comment' => 'نمایش نظر',
        'create_delivery' => 'ایجاد روش ارسال',
        'delivery' => 'روش های ارسال',
        'create_amazing_discount' => 'ایجاد فروش شگفت انگیز',
        'sale_amazing' => 'فروش شگفت انگیز',
        'create_public_discount' => 'ایجاد تخفیف عمومی',
        'public_discount' => 'تخفیف عمومی',
        'create_copan_discount' => 'ایجاد کوپن تخفیف',
        'copan' => 'کوپن تخفیف',
        'order' => 'سفارشات',
        'payment' => 'پرداخت ها',
        'product' => 'کالاها',
        'create_product' => 'ایجاد کالا',
        'property' => 'فرم کالا',
        'create_property' => 'ایجاد فرم کالا',
        'store' => 'انبار',
        'add_store' => 'اضافه کردن به انبار',
        'faq_index' => 'سوالات متداول',
        'faq_create' => 'ایجاد سوال',
        'faq_edit' => 'ویرایش سوال',
        'menu_index' => 'منو',
        'menu_create' => 'ایجاد منو',
        'page_index' => 'پیج ساز',
        'page_create' => 'ایجاد پیج',
        'page_edit' => 'ویرایش پیج',
        'post_index' => 'پست ها',
        'post_create' => 'ایجاد پست',
        'post_edit' => 'ویرایش پست',
        'admin_user_index' => 'کاربران ادمین',
        'admin_user_create' => 'ایجاد ادمین جدید',
        'customer_index' => 'مشتریان',
        'customer_create' => 'ایجاد مشتری جدید',
        'role_index' => 'نقش ها',
        'role_create' => 'ایجاد نقش ',
        'email_index' => 'اطلاعیه ایمیل',
        'email_create' => 'ایجاد ایمیل',
        'sms_index' => 'اطلاعیه پیامکی',
        'sms_create' => 'ایجاد پیامک',
        'ticket_index' => 'تیکت',
        'ticket_show' => 'نمایش تیکت',
        'setting_index' => 'تنظیمات',
    ]
];


?>
