<?php

return [
    'page_title' => [
        'create_brand' => 'ایجاد برند',
        'edit_brand' => 'ویرایش برند',
        'brand' => 'برندها',
        'create_category' => 'ایجاد دسته بندی',
        'edit_category' => 'ویرایش دسته بندی',
        'category' => 'دسته بندی',
        'comment' => 'نظرات',
        'show_comment' => 'نمایش نظر',
        'create_delivery' => 'ایجاد روش ارسال',
        'edit_delivery' => 'ویرایش روش ارسال',
        'delivery' => 'روش های ارسال',
        'create_amazing_discount' => 'ایجاد فروش شگفت انگیز',
        'sale_amazing' => 'فروش شگفت انگیز',
        'create_public_discount' => 'ایجاد تخفیف عمومی',
        'public_discount' => 'تخفیف عمومی',
        'create_copan_discount' => 'ایجاد کوپن تخفیف',
        'copan' => 'کوپن تخفیف',
        'order' => 'سفارشات',
        'payment' => 'پرداخت ها',
        'product' => 'کالاها',
        'create_product' => 'ایجاد کالا',
        'edit_product' => 'ویرایش کالا',
        'form_property' => 'ویژگی فرم کالا',
        'property' => 'فرم کالا',
        'create_property' => 'ایجاد فرم کالا',
        'edit_property' => 'ویرایش فرم کالا',
        'store' => 'انبار',
        'add_store' => 'اضافه کردن به انبار',
        'faq_index' => 'سوالات متداول',
        'faq_create' => 'ایجاد سوال',
        'faq_edit' => 'ویرایش سوال',
        'menu_index' => 'منو',
        'menu_create' => 'ایجاد منو',
        'menu_edit' => 'ویرایش منو',
        'page_index' => 'پیج ساز',
        'page_create' => 'ایجاد پیج',
        'page_edit' => 'ویرایش پیج',
        'post_index' => 'پست ها',
        'post_create' => 'ایجاد پست',
        'post_edit' => 'ویرایش پست',
        'admin_user_index' => 'کاربران ادمین',
        'admin_user_create' => 'ایجاد ادمین جدید',
        'admin_user_edit' => 'ویرایش ادمین جدید',
        'customer_user_index' => 'مشتریان',
        'customer_user_create' => 'ایجاد مشتری جدید',
        'customer_user_edit' => 'ویرایش مشتری جدید',
        'role_index' => 'نقش ها',
        'role_create' => 'ایجاد نقش ',
        'role_edit' => 'ویرایش نقش ',
        'role_permission' => 'دسترسی های نقش ',
        'email_index' => 'اطلاعیه ایمیل',
        'email_create' => 'ایجاد ایمیل',
        'email_edit' => 'ویرایش ایمیل',
        'sms_index' => 'اطلاعیه پیامکی',
        'sms_create' => 'ایجاد پیامک',
        'sms_edit' => 'ویرایش پیامک',
        'ticket_category_index' => 'دسته بندی',
        'ticket_priority_index' => 'اولویت',
        'ticket_category_create' => 'ایجاد دسته بندی',
        'ticket_priority_create' => 'ایجاد اولویت',
        'ticket_category_edit' => 'ویرایش دسته بندی',
        'ticket_priority_edit' => 'ویرایش اولویت ',
        'ticket_admin_index' => 'ادمین تیکت',
        'ticket_index' => 'تیکت ها',
        'ticket_show' => 'نمایش تیکت',
        'setting_index' => 'تنظیمات',
        'setting_edit' => 'ویرایش تنظیمات',
        'public_email_file' => 'فایلهای ایمیل',
        'email_file_create' => 'ایجاد فایل اطلاعیه ایمیلی',
        'email_file_edit' => 'ویرایش فایل اطلاعیه ایمیلی',
        'product_color_index' => 'رنگ محصولات',
        'product_color_create' => 'ایجاد رنگ',
        'product_gallery_index' => 'تصاویر محصول',
        'product_gallery_create' => 'ایجاد تصویر',
    ]
];


?>
